robopi:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    effort:
      wheel_left:
        type: effort_controllers/JointEffortController
        joint: wheel_left
        pid: {p: 0.1, i: 0, d: 0.0}
      wheel_right:
        type: effort_controllers/JointEffortController
        joint: wheel_right
        pid: {p: 0.1, i: 0, d: 0.0}