robopi:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      left_wheel:
        type: effort_controllers/JointVelocityController
        joint: gpio_wheel
        pid: {p: 10.0, i: 0.0, d: 1.0}
      right_wheel:
        type: effort_controllers/JointVelocityController
        joint: gpio_wheel
        pid: {p: 5.0, i: 2.0, d: 1.0}