robopi:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    effort:
      wheel_left:
        type: effort_controllers/JointEffortController
        joint: wheel_left
      wheel_right:
        type: effort_controllers/JointEffortController
        joint: wheel_right
