robopi:
  actuator_interface:
    loop_hz: 10 # hz
    wheels:
      - wheel_left
      - wheel_right
  gpio_wheels:
    wheel_left:
      en: 21
      inF: 20
      inB: 16
    wheel_right:
      en: 13
      inF: 26
      inB: 19